language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - ANTELOPE_CATALOG_ROOT="./CATALOG_ROOT"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install pip==20.1; fi
install:
  - pip install coverage coveralls
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install --no-deps -r test_requirements_nodeps.txt
script:
  - coverage run --source=antelope_core -m unittest
after_success:
  - coveralls
