language: python
python:
  - "3.7"
env:
  - ANTELOPE_CATALOG_ROOT="./CATALOG_ROOT"
install:
  - pip install coverage coveralls
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install --no-deps -r test_requirements_nodeps.txt
script:
  - coverage run --source=antelope_core -m unittest
after_success:
  coveralls
