language: python
python:
  - "3.7"
install:
  - pip install coverage coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source=antelope_core -m unittest
after_success:
  coveralls
